Added Button component and renamed the folder 'component' to 'compone…
marlonmionb/virtual-book-shelf pull request #13
Opened 2024-04-30 15:39 UTC by LucasJann

![button test](https://github.com/marlonmionb/virtual-book-shelf/assets/114890658/3060363a-2ddf-4348-8464-fb3bd047b624)

2024-04-30 16:18 UTC, marlonmionb requested changes
Nice Work!

2024-04-30 16:18 UTC, marlonmionb commented on src/components/Button/Button.tsx
> +const Button: React.FC<ButtonProps> = (props) => {
`const Button: React.FC<ButtonProps> = ({children, type = 'button', onClick}) => {`

You can avoid the usage of props here, in typescript is better if you describe every object. Also you can set a value as default with the "=" and avoid conditional logic in the component.

2024-04-30 16:18 UTC, marlonmionb commented on src/components/Button/Button.tsx
> +        type={props.type || 'button'}
If you set the 'button' as type default you can simply:
`type={type}`

2024-04-30 16:18 UTC, marlonmionb commented on src/components/Button/Button.tsx
> +        onClick={props.onClick}
This would be:
OnClick={onClick}

2024-04-30 16:18 UTC, marlonmionb commented on src/components/Button/Button.tsx
> +        {props.children}
{children}

2024-04-30 16:18 UTC, marlonmionb commented on package.json
> +    "@types/testing-library__react": "^10.2.0",
Do we need this dependency?
Dependency updates and changes need their own Issue/branch

2024-04-30 16:20 UTC, marlonmionb requested changes

2024-04-30 16:20 UTC, marlonmionb commented on src/App.tsx
> +import { Fragment } from "react/jsx-runtime"
We should not include changes in the app.jsx, only the component itself

2024-04-30 16:40 UTC, LucasJann commented on src/App.tsx
> +import { Fragment } from "react/jsx-runtime"
This change is important because if you render more than one component, the code will not work warning an error. To fix that error you will need add a <div> to handle with this two components, example:

This not work:
return (
       <Button>1</Button>
       <Button>2</Button>
)

This works, but it's too old sintaxe
return (
      <div>
               <Button>1</Button>
               <Button>2</Button>
      </div>
)

This works and it's the current sintaxe
 return (
    <Fragment>
        <Button onClick={consoleLog}>+ New Post</Button>
        <Button onClick={consoleLog}>+ New Book</Button>
    </Fragment>
  )
  
  Fragment is the React's <div>

2024-05-01 16:55 UTC, marlonmionb approved these changes

2024-05-02 18:54 UTC, merged